export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'

export const GET_LAST_ARTICLES = 'GET_LAST_ARTICLES'
export const GET_LAST_ARTICLES_SUCCESS = 'GET_LAST_ARTICLES_SUCCESS'

export const GET_LAST_PAGE = 'GET_LAST_PAGE'
export const GET_LAST_PAGE_SUCCESS = 'GET_LAST_PAGE_SUCCESS'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_LAST_PAGE = 'GET_LAST_PAGE'

export const GET_BOARD_LIST_SUCCESS = 'GET_BOARD_LIST_SUCCESS'
